#!/bin/bash

## JOB NAME
#PBS -N workshop_test
## QUEUE NAME
#PBS -q regularq
## COMPUTE RESOURCES REQUESTED FOR THE JOB SELECT = NO. OF CHUNKS/NODES, NCPUS = NO. OF CORES PER CHUNK/NODE
#PBS -l select=1:ncpus=40
## SPECIFY THE EXECUTION TIME LIMIT FOR THE CODE/APPLICATION IN HRS:MINS:SECS FORMAT
#PBS -l walltime=00:30:00
## JOIN THE OUTPUT AND ERROR FILES INTO A SINGLE FILE WITH NAME <JOBNAME>.O<JOBID>
#PBS -j oe
## EXPORT ALL ENVIRONMENT VARIABLES
#PBS -V
#EMAIL IS SENT WHEN THE JOB STARTS, TERMINATES AND ABORTS
#PBS -m bea
## SPECIFY EMAIL ADDRESS FOR NOTIFICATIONS
#PBS -M abc@ipr.res.in


# LOAD A MODULE BASED ON APPLICATION/CODE REQUIREMENT
module load intel-2020
source /home/application/intel-2020/parallel_studio_xe_2020.1.102/psxevars.sh
# ENVIRONMENT VARIABLE FOR ACCESSING THE WORKING DIRECTORY WITH PBS VARIABLE
cd $PBS_O_WORKDIR

# WRITE IN NODES.TXT FILE, THE NODES ON WHICH THE RUN HAS BEEN LAUNCHED
#cat ${PBS_NODEFILE} > /scratch/scratch_data/deepakagg/queue_testing/nodes.txt

# RUN COMMAND BASED ON CODE/APPLICATION
sh v0.sh

